### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1

### ISSUE THREAD

**Issue by thehighestend** [haoheliu/versatile_audio_super_resolution#19]
I'm getting this error when converting the attached file:

`DDIM Sampler:   0%|                                                                              | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/audiosr/bin/audiosr", line 107, in <module>
    waveform = super_resolution(
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/audiosr/pipeline.py", line 167, in super_resolution
    waveform = latent_diffusion.generate_batch(
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/audiosr/latent_diffusion/models/ddpm.py", line 1524, in generate_batch
    samples, _ = self.sample_log(
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/audiosr/latent_diffusion/models/ddpm.py", line 1430, in sample_log
    samples, intermediates = ddim_sampler.sample(
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/audiosr/latent_diffusion/models/ddim.py", line 143, in sample
    samples, intermediates = self.ddim_sampling(
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/audiosr/latent_diffusion/models/ddim.py", line 237, in ddim_sampling
    outs = self.p_sample_ddim(
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/audiosr/latent_diffusion/models/ddim.py", line 293, in p_sample_ddim
    model_t = self.model.apply_model(x_in, t_in, c)
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/audiosr/latent_diffusion/models/ddpm.py", line 1029, in apply_model
    x_recon = self.model(x_noisy, t, cond_dict=cond)
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/audiosr/latent_diffusion/models/ddpm.py", line 1685, in forward
    out = self.diffusion_model(
  File 
"/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/username/miniconda3/envs/audiosr/lib/python3.9/site-packages/audiosr/latent_diffusion/modules/diffusionmodules/openaimodel.py", line 879, in forward
    h = th.cat([h, concate_tensor], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 63 for tensor number 1 in the list.`

[S.zip](https://github.com/haoheliu/versatile_audio_super_resolution/files/12697411/S.zip)

**Comment by susanin-ivan** [comment]
Hi @thehighestend ,

Your WAV is too short, as it seems:

_Input #1, wav, from 'S.WAV':
  Duration: 00:00:01.02, bitrate: 176 kb/s
  Stream #1:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 22050 Hz, 1 channels, u8, 176 kb/s_

Adding to it 0.1s padding allows to process it:

`ffmpeg -i S.WAV -acodec pcm_u8 -ac 1 -af "apad=pad_dur=0.01" S_8u_pad0.WAV`

Which will convert your file to this:

_Input #0, wav, from 'S_8u_pad0.WAV':
  Metadata:
    encoder         : Lavf60.12.101
  Duration: 00:00:01.03, bitrate: 177 kb/s
  Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 22050 Hz, 1 channels, u8, 176 kb/s_

Then it works:

`audiosr -i S_8u_pad0.WAV --ddim_steps 100 --seed 0123456789 `

_Loading AudioSR: basic
Loading model on cuda:0
...
Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:09<00:00, 10.42it/s]
Don't forget to try different seeds by setting --seed <int> so that AudioSR can have optimal performance on your hardware.
Save audio to ./output/22_09_2023_10_19_36/S_8u_pad0_AudioSR_Processed_48K.wav._

Please be aware that you'll get an 5.12 seconds and pcm_s16le output file at the end:

_Input #0, wav, from './output/22_09_2023_10_19_36/S_8u_pad0_AudioSR_Processed_48K.wav':
  Duration: 00:00:05.12, bitrate: 768 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 1 channels, s16, 768 kb/s_

Hope this helps

**Comment by thehighestend** [comment]
Okay, that surely helped.
I'm closing this issue.

**Comment by thehighestend** [comment]
Okay, that workaround surely helped.
I'm closing this issue.
