### ISSUE TITLE
Numpy "float" issue

### ISSUE THREAD

**Issue by MikeGO2611** [haoheliu/versatile_audio_super_resolution#36]
I'm able to run it in CPU and Cuda, the DDIM Sampler reaches 100%, but then this error displays and the output folder is empty.

```
Traceback (most recent call last):
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\audiosr\__main__.py", line 115, in <module>
    waveform = super_resolution(
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\audiosr\pipeline.py", line 168, in super_resolution
    waveform = latent_diffusion.generate_batch(
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddpm.py", line 1546, in generate_batch
    waveform = self.postprocessing(waveform, waveform_lowpass)
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddpm.py", line 1595, in postprocessing
    out_renewed = librosa.istft(stft_out, length=length)
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\librosa\core\spectrum.py", line 394, in istft
    dtype = util.dtype_c2r(stft_matrix.dtype)
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\librosa\util\utils.py", line 2185, in dtype_c2r
    np.dtype(complex): np.dtype(np.float).type,
  File "C:\Users\Miguel\miniconda3\envs\audiosr\lib\site-packages\numpy\__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by zslittlehelper** [comment]
I'm guessing that you've installed a cuda enabled version of pytorch, which in turn installs a version of numpy which this repo doesn't support (version 1.23.5 vs 1.26)

One way, which I used to work around the issue, is to force install the old numpy version: pip install numpy==1.23.5 --force

**Comment by MikeGO2611** [comment]
> I'm guessing that you've installed a cuda enabled version of pytorch, which in turn installs a version of numpy which this repo doesn't support (version 1.23.5 vs 1.26)
> 
> One way, which I used to work around the issue, is to force install the old numpy version: pip install numpy==1.23.5 --force

Yes, I've installed Cuda. I've reinstalled numpy with the command you shared and it does not return that error. Thanks!
