### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 63 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by vb87** [haoheliu/versatile_audio_super_resolution#37]
I'm using the latest master and running on CUDA.

Here's the mp3 file I'm using as input:
[](https://drive.google.com/file/d/1xR2mV-SctUknIvjKqlTYyFKHRl5annCX/view?usp=sharing
)

command line:
`audiosr -i 5.01_22303.037073170733_23517.438009756097.mp3 -s . -d cuda`

getting this error:

> DDIM Sampler:   0%|                                                                                                                 | 0/50 [00:02<?, ?it/s]
> Traceback (most recent call last):
>   File "D:\anaconda3\envs\audiosr\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "D:\anaconda3\envs\audiosr\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\__main__.py", line 115, in <module>
>     waveform = super_resolution(
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\pipeline.py", line 168, in super_resolution
>     waveform = latent_diffusion.generate_batch(
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddpm.py", line 1525, in generate_batch
>     samples, _ = self.sample_log(
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddpm.py", line 1431, in sample_log
>     samples, intermediates = ddim_sampler.sample(
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddim.py", line 143, in sample
>     samples, intermediates = self.ddim_sampling(
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddim.py", line 237, in ddim_sampling
>     outs = self.p_sample_ddim(
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddim.py", line 293, in p_sample_ddim
>     model_t = self.model.apply_model(x_in, t_in, c)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddpm.py", line 1030, in apply_model
>     x_recon = self.model(x_noisy, t, cond_dict=cond)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddpm.py", line 1686, in forward
>     out = self.diffusion_model(
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "D:\anaconda3\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\modules\diffusionmodules\openaimodel.py", line 889, in forward
>     h = th.cat([h, concate_tensor], dim=1)
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 63 for tensor number 1 in the list.
>

**Comment by yuzuda283** [comment]
same question

**Comment by Susukerow45** [comment]
try 0.512 sec wav file

**Comment by DrJackPayne** [comment]
Ran into this as well.  It seems to be related to the audio file being too short.  If you pad the input audio array with some trailing zeros it should function.
