### ISSUE TITLE
Cannot find file specified?

### ISSUE THREAD

**Issue by dillfrescott** [haoheliu/versatile_audio_super_resolution#55]
```python
Save audio to ./output\31_05_2024_01_31_19\clip_AudioSR_Processed_48K.wav.
Traceback (most recent call last):
  File "C:\Users\cross\miniconda3\envs\upscaler\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cross\miniconda3\envs\upscaler\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\cross\miniconda3\envs\upscaler\lib\site-packages\audiosr\__main__.py", line 123, in <module>
    save_wave(waveform, inputpath=input_file, savepath=save_path, name=name, samplerate=sample_rate)
  File "C:\Users\cross\miniconda3\envs\upscaler\lib\site-packages\audiosr\utils.py", line 315, in save_wave
    strip_silence(inputpath, temp_path, save_path)
  File "C:\Users\cross\miniconda3\envs\upscaler\lib\site-packages\audiosr\utils.py", line 263, in strip_silence
    get_dur = subprocess.run([
  File "C:\Users\cross\miniconda3\envs\upscaler\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\cross\miniconda3\envs\upscaler\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\cross\miniconda3\envs\upscaler\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by dillfrescott** [comment]
Seemed to have been related to how ffmpeg was detected on my PATH.

Running `conda install ffmpeg` seemed to have fixed it.
