### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by AmirDanil** [haoheliu/versatile_audio_super_resolution#56]
im having the same issue with my local Pycharm and also on GitGub CodeSpaces . 
my input is 5 seconds lenght audio with mp3 format & wav formats. trying to insert each of the code but got the same error every time : 
@AmirDanil ➜ /workspaces/versatile_audio_super_resolution/bin (main) $ python audiosr -i /workspaces/versatile_audio_super_resolution/
bin/stars.wav -s /workspaces/versatile_audio_super_resolution/bin
/home/codespace/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading AudioSR: basic
Loading model on cpu
/home/codespace/.local/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/codespace/.local/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py:611: UserWarning: Argument 'onesided' has been deprecated and has no influence on the behavior of this module.
  warnings.warn(
DiffusionWrapper has 258.20 M params.
Running DDIM Sampling with 50 timesteps
DDIM Sampler: 100%|████████████████| 50/50 [01:01<00:00,  1.23s/it]
 Don't forget to try different seeds by setting --seed <int> so that AudioSR can have optimal performance on your hardware.
Save audio to /workspaces/versatile_audio_super_resolution/bin/01_06_2024_07_01_02/stars_AudioSR_Processed_48K.wav.
Traceback (most recent call last):
  File "/workspaces/versatile_audio_super_resolution/bin/audiosr", line 123, in <module>
    save_wave(waveform, inputpath=input_file, savepath=save_path, name=name, samplerate=sample_rate)
  File "/home/codespace/.local/lib/python3.10/site-packages/audiosr/utils.py", line 315, in save_wave
    strip_silence(inputpath, temp_path, save_path)
  File "/home/codespace/.local/lib/python3.10/site-packages/audiosr/utils.py", line 263, in strip_silence
    get_dur = subprocess.run([
  File "/usr/local/python/3.10.13/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/python/3.10.13/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python/3.10.13/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

**Comment by kemonstudio** [comment]
Run the following command to install ffmpeg from the conda-forge channel :

conda install -c conda-forge ffmpeg

The error suggests that ffmpeg might not be installed or not in the system's PATH.
