### ISSUE TITLE
Installation error on ubuntu 

### ISSUE THREAD

**Issue by shikida** [haoheliu/versatile_audio_super_resolution#58]
any idea on how to fix this?

```
Requirement already satisfied: mdurl~=0.1 in /home/leo/.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio->-r requirements.txt (line 11)) (0.1.2)

Building wheels for collected packages: diffusers, progressbar, ffmpy, pylatexenc

  Building wheel for diffusers (pyproject.toml) ... done

  Created wheel for diffusers: filename=diffusers-0.30.0.dev0-py3-none-any.whl size=2226068 sha256=4f76067d31c6be6a62231ffbae2d150e6d371e99c16de14f13f15ace521811e8

  Stored in directory: /tmp/pip-ephem-wheel-cache-7m4oojtu/wheels/4d/b7/a8/6f9549ceec5daad78675b857ac57d697c387062506520a7b50

  Building wheel for progressbar (setup.py) ... done

  Created wheel for progressbar: filename=progressbar-2.5-py3-none-any.whl size=12082 sha256=06435d1c8074e804415f42e7300ef5faf8d56843d8af4be073d225187106cedd

  Stored in directory: /home/leo/.cache/pip/wheels/cd/17/e5/765d1a3112ff3978f70223502f6047e06c43a24d7c5f8ff95b

  Building wheel for ffmpy (setup.py) ... done

  Created wheel for ffmpy: filename=ffmpy-0.3.2-py3-none-any.whl size=5600 sha256=5ab0c3bcd71e2c7b55ec277ea53c14a57d4164691540ea3e534fead1d073d3fa

  Stored in directory: /home/leo/.cache/pip/wheels/bd/65/9a/671fc6dcde07d4418df0c592f8df512b26d7a0029c2a23dd81

  Building wheel for pylatexenc (setup.py) ... done

  Created wheel for pylatexenc: filename=pylatexenc-2.10-py3-none-any.whl size=136835 sha256=bbe20735a7676ae9a354e4975eaeb72121e4ae0a20973abb39cc2ad48cee802e

  Stored in directory: /home/leo/.cache/pip/wheels/d3/31/8b/e09b0386afd80cfc556c00408c9aeea5c35c4d484a9c762fd5

Successfully built diffusers progressbar ffmpy pylatexenc

ERROR: Exception:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper

    status = run_func(*args)

  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper

    return func(self, options, args)

  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run

    to_install = resolver.get_installation_order(requirement_set)

  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order

    weights = get_topological_weights(

  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights

    assert len(weights) == expected_node_count

AssertionError

leo@ubuntu:~/versatile_audi
```

**Comment by shikida** [comment]
it was an outdated pip version.
